// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using se.Urbaino.ShipBattles.Data;

namespace se.Urbaino.ShipBattles.Data.Migrations
{
    [DbContext(typeof(ShipBattlesContext))]
    [Migration("20180810071458_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("se.Urbaino.ShipBattles.Data.DBO.GameDBO", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("HeightA");

                    b.Property<int>("HeightB");

                    b.Property<string>("JSONShipsA");

                    b.Property<string>("JSONShipsB");

                    b.Property<string>("JSONShotsA");

                    b.Property<string>("JSONShotsB");

                    b.Property<string>("PlayerA");

                    b.Property<int>("PlayerAState");

                    b.Property<string>("PlayerB");

                    b.Property<int>("PlayerBState");

                    b.Property<DateTime>("Timestamp");

                    b.Property<int>("WidthA");

                    b.Property<int>("WidthB");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
